describe("JohnWickTest", () => {
  it("tests JohnWickTest", () => {
    cy.viewport(1268, 937);
    cy.visit("http://localhost:8080/");
    cy.get("div:nth-of-type(3) > div:nth-of-type(1) input").click();
    cy.get("div:nth-of-type(3) > div:nth-of-type(1) input").type("Honh");
    cy.get("div:nth-of-type(4) > div:nth-of-type(1) input").click();
    cy.get("div:nth-of-type(4) > div:nth-of-type(1) input").type("Wick");
    cy.get("div:nth-of-type(2) > div.MuiBox-root").click();
    cy.get("div:nth-of-type(3) > div:nth-of-type(1) input").click();
    cy.get("div:nth-of-type(3) > div:nth-of-type(1) input").type("John");
    cy.get("#app > div > div:nth-of-type(2)").click();
    cy.get("div:nth-of-type(4) > div:nth-of-type(2) input").click();
    cy.get("div:nth-of-type(4) > div:nth-of-type(2) input").type("9888888888");
    cy.get("div > div > div > div:nth-of-type(2) button").click();
    cy.get("#mui-component-select-Language").dblclick();
    cy.get("div:nth-of-type(12) > button").click();
    cy.get("div:nth-of-type(11) > button").click();
    cy.get("div:nth-of-type(11) > button").click();
    cy.get("div:nth-of-type(2) > div div.MuiContainer-root").click();
    cy.get("span > div path").click();
    cy.get("#mui-5").click();
    cy.get("#mui-5").click();
    cy.get("#mui-5").type("01/01/1997");
    cy.get("#mui-6").click();
    cy.get("#mui-6").type("demonslayer@gmail.com");
    cy.get("#gender").click();
    cy.get("li:nth-of-type(4)").click();
    cy.get("button:nth-of-type(2) path").click();
    cy.get("#mui-component-select-state").click();
    cy.get("li:nth-of-type(5)").click();
    cy.get("#mui-component-select-district").click();
    cy.get("#menu-district > div.MuiBackdrop-root").click();
    cy.get("#mui-component-select-district").click();
    cy.get("li:nth-of-type(3)").click();
    cy.get("#city").click();
    cy.get("#city").type("Wash.D.C");
    cy.get("#pin_code").click();
    cy.get("#pin_code").type("11222");
    cy.get("#mui-component-select-current_status").click();
    cy.get("li:nth-of-type(4)").click();
    cy.get("#mui-component-select-qualification").click();
    cy.get("li:nth-of-type(5)").click();
    cy.get("#mui-7").click();
    cy.get("#mui-7").type("99.99");
    cy.get("#mui-8").click();
    cy.get("#mui-8").type("99.99");
    cy.get("#mui-component-select-school_medium").click();
    cy.get("li:nth-of-type(3)").click();
    cy.get("#mui-component-select-caste").click();
    cy.get("li:nth-of-type(4)").click();
    cy.get("#mui-component-select-religion").click();
    cy.get("li:nth-of-type(8)").click();
    cy.get("#mui-component-select-religion").click();
    cy.get("li:nth-of-type(7)").click();
    cy.get("[data-testid='KeyboardArrowRightIcon']").click();
    cy.get("#pin_code").type("4402xx");
    cy.get("#app > div > div:nth-of-type(2) button.MuiButton-contained").click();
  });
});
