export const baseUrl = `${import.meta.env.VITE_API_URL}`;

export const customPartner = ["amravati", "lahia"];
export const testClosed = {
  partners: [],
  message: "Tests have now been closed!",
};

export const permissions = {
  permissionsView: ["kirithiv@navgurukul.org", "vaibhavmagar@navgurukul.org"],
  updateStage: [
    "rupakumari20@navgurukul.org",
    "sapnapandey20@navgurukul.org",
    "reena@navgurukul.org",
    "tarun20@navgurukul.org",
    "vishnusharma@navgurukul.org",
    "amarjeetg22@navgurukul.org",
    "jyotisharma22@navgukul.org",
    "anjalit22@navgurkul.org",
    "kankana@navgutukul.org",
    "rajalakshmi@navgurukul.org",
    "ishita@navgurukul.org",
    "anzum20@navgurukul.org",
    "chuningliu21@navgurukul.org",
    "vijay@navgurukul.org",
    "vishnu@navgurukul.org",
    "samyukta@navgurukul.org",
    "tahniyatnisar21@navgurukul.org",
    "shreshta@navgurukul.org",
    "anarkat@navgurukul.org",
    "pihu20@navgurukul.org",
    "richa@navgurukul.org",
    "admission@navgurukul.org",
    "anushkag20@navgurukul.org",
    "nidhi@navgurukul.org",
    "manisha@navgurukul.org",
    "saquib@navgurukul.org",
    "swanand@navgurukul.org",
    "kirithiv@navgurukul.org",
    "saquib18@navgurukul.org",
    "kirithivr19@navgurukul.org",
    "anand@navgurukul.org",
    "komala@navgurukul.org",
    "poonam@navgurukul.org",
    "r@navgurukul.org",
    "s@navgurukul.org",
    "nilam@navgurukul.org",
    "a@navgurukul.org",
    "nitesh@navgurukul.org",
    "kumar19@navgurukul.org",
    "lalita17@navgurukul.org",
    "ranis19@navgurukul.org",
    "Peter19@navgurukul.org",
    "rahit@navgurukul.org",
    "aman18@navgurukul.org",
    "aman@navgurukul.org",
    "shivanimalviya20@navgurukul.org",
    "rubina20@navgurukul.org",
    "kittiy@navgurukul.org",
    "rose@navgurukul.org",
    "komal@navgurukul.org",
    "komal18@navgurukul.org",
    "pooja@navgurukul.org",
    "vimla20@navgurukul.org",
    "sanjana20@navgurukul.org",
    "anamika20@navgurukul.org",
    "shahnaaz@navgurukul.org",
    "bhartikumari20@navgurukul.org",
    "shweta@navgurukul.org",
    "subhash20@navgurukul.org",
    "ranjan20@navgurukul.org",
    "kumar@navgurukul.org",
    "pranjali20@navgurukul.org",
    "kalpana20@navgurukul.org",
    "shahina@navgurukul.org",
    "ranjana20@navgurukul.org",
    "shreshta20@navgurukul.org",
    "usha20@navgurukul.org",
    "ishitav20@navgurukul.org",
    "somisingh20@navgurukul.org",
    "meghakashyap20@navgurukul.org",
    "shanti@navgurukul.org",
    "swati@navgurukul.org",
    "himani21@navgurukul.org",
    "reena20@navgurukul.org",
    "mohammedsana20@navgurukul.org",
    "anshika21@navgurukul.org",
    "ruchi20@navgurukul.org",
    "jayshrirathod20@navgurukul.org",
    "ayushi21@navgurukul.org",
    "shubhangimhetre20@navgurukul.org",
    "priyankadangwal20@navgurukul.org",
    "riyasingh21@navgurukul.org",
    "nasringulnaaz21@navgurukul.org",
    "sindhu@navgurukul.org",
    "Himalik@navgurukul.org",
    "sweetyparveen21@navgurukul.org",
    "shikha21@navgurukul.org",
    "vaibhavmagar@navgurukul.org",
    "sweetyparveen21@navgurukul.org",
    "riyasingh21@navgurukul.org",
    "sushreesupriti21@navgurukul.org",
    "astha@navgurukul.org",
    "Pihu20@navgurukul.org",
    "Dorababu@navgurukul.org",
    "Pranav@navgurukul.org",
    "vikash21@navgurukul.org",
    "kajalk20@navgurukul.org",
    "anoj@navgurukul.org",
    "kartik@navgurukul.org",
    "satish21@navgurukul.org",
    "pratik18@navgurukul.org",
  ],

  updateStudentName: [
    "shikha21@navgurukul.org",
    "rupalisingh@navgurukul.org",
    "kittiy@navgurukul.org",
    "komal@navgurukul.org",
    "shreshta20@navgurukul.org",
    "kumar@navgurukul.org",
    "rahit@navgurukul.org",
    "shweta@navgurukul.org",
    "shahnaaz@navgurukul.org",
    "saquib@navgurukul.org",
    "saquib18@navgurukul.org",
    "rose@navgurukul.org",
    "nilam@navgurukul.org",
    "kittiy@navgurukul.org",
    "samyukta@navgurukul.org",
    "pooja@navgurukul.org",
    "shahina@navgurukul.org",
    "ranjana20@navgurukul.org",
    "pranjali20@navgurukul.org",
    "anshika21@navgurukul.org",
    "riyasingh21@navgurukul.org",
    "nasringulnaaz21@navgurukul.org",
    "sindhu@navgurukul.org",
    "Himalik@navgurukul.org",
    "kirithiv@navgurukul.org",
    "sweetyparveen21@navgurukul.org",
    "shikha21@navgurukul.org",
    "vaibhavmagar@navgurukul.org",
    "sweetyparveen21@navgurukul.org",
    "nitesh@navgurukul.org",
  ],
  addOrUpdateContact: [
    "kittiy@navgurukul.org",
    "rahit@navgurukul.org",
    "nilam@navgurukul.org",
    "nitesh@navgurukul.org",
    "kumar@navgurukul.org",
  ],
};

export const allStages = {
  // related to the mcq test
  enrolmentKeyGenerated: "Enrolment Key Generated",
  createdStudentWithoutExam: "Created Student Without Exam",
  basicDetailsEntered: "Basic Details Entered",
  // english interviews
  pendingEnglishInterview: "English Interview Pending (2nd Round)",
  // forReviewEnglishInterview: "English Interview For Review",
  englishInterviewFail: "English Interview Failed",
  // englishInterviewWaitlisted: "English Interview Waitlisted",

  // algebra interviews
  pendingAlgebraInterview: "Algebra Interview Pending (3rd Round)",
  // forReviewAlgebraInterviewDone: "Algebra Interview For Review",
  algebraInterviewFail: "Algebra Interview Failed",
  // algebraInterviewWaitlisted: "Algebra Interview Waitlisted",

  // culture fit interviews
  pendingCultureFitInterview: "Culture Fit Interview Pending (4th Round)",

  // cultureFitInterviewWaitlisted: "Culture Fit Interview Waitlisted",
  pendingCultureFitReinterview: "Pending Culture Fit Re-Interview",
  cultureFitInterviewFail: "Culture Interview Failed",

  // parent conversations
  pendingParentConversation: "Pending Parent Conversations",
  parentConversationFail: "Parent Conversation Failed",

  // selection
  selected: "Selected",
  selectedAndJoiningAwaited: "Selected & Joining Awaited",
  selectedButNotJoined: "Selected But Not Joined",
  offerLetterSent: "Offer Letter Sent",

  // travel planning
  pendingTravelPlanning: "Pending Travel Plans",
  finalisedTravelPlans: "Finalized Travel Plans",

  // probation etc. once when the student has joined navgurukul
  // probation: "Probation",
  deferredJoining: "Deferred Joining",
  finallyJoined: "Joined",
  // droppedOut: "Dropped Out",
  // sentBackAfterProbation: "Probation Failed",

  // is not reachable
  becameDisIntersested: "Became Disinterested",
  // disqualifiedUnreachable: "Can`t reach Student",
  notReachable: "Unreachable",

  // diversity based decision
  disqualifiedAfterDiversityFilter: "Diversity Failed",
  diversityBasedDecisionPending: "Decision Pending based on Diversity",

  // random stages for internal use
  possibleDuplicate: "Duplicate",
  // needAction: "Need Action",
  // demo: "Not Clear???",
  caughtCheating: "Caught Cheating",
  tuitionGroup: "Tution Group",

  requestCallback: "Requested Callback",
  // pendingCallbackForQuery: "Pending Callback",
  // forReviewCallbackQueryResolved: "For Review CallbackQuery Resolved",
  queryResolvedAfterCallback: "Query Resolved After CallBack",
  testFailed: "Test Failed",
  M1: "English & Quarantine",
  M2: "Dry Run",
  M3: "If - Else",
  M4: "Loops",
  M5: "Lists",
  M6: "Functions",
  M7: "Python Complete",
  M8: "Hangman, Requests & more",
  M9: "Web Scraping",
  M10: "Javascript / ES6",
  M11: "NodeJS - Callbacks & Async",
  M12: "React - HTML & CSS",
  M13: "NodeJS - CRUD",
  M14: "React - Bootstrap & Jquery",
  M15: "NodeJS - MySQL/Knex/Joi",
  M16: "React - State, Props & Components",
  M17: "NodeJS: JWT",
  M18: "React - React Lifecycle",
  M19: "Project 1",
  M20: "Project 2",
  M21: "Interview Preparation",
  M22: "Job Search",
  onLeave: "On Leave",
  droppedOut: "Dropped Out",
  inJob: "In Job",
  payingForward: "Paying Forward",
  paidForward: "Paid Forward",
};

export const campusStageOfLearning = {
  finallyJoined: "Joined",
  M1: "English & Quarantine",
  M2: "Dry Run",
  M3: "If - Else",
  M4: "Loops",
  M5: "Lists",
  M6: "Functions",
  M7: "Python Complete",
  M8: "Hangman, Requests & more",
  M9: "Web Scraping",
  M10: "Javascript / ES6",
  M11: "NodeJS - Callbacks & Async",
  M12: "React - HTML & CSS",
  M13: "NodeJS - CRUD",
  M14: "React - Bootstrap & Jquery",
  M15: "NodeJS - MySQL/Knex/Joi",
  M16: "React - State, Props & Components",
  M17: "NodeJS: JWT",
  M18: "React - React Lifecycle",
  M19: "Project 1",
  M20: "Project 2",
  M21: "Interview Preparation",
  M22: "Job Search",
  onLeave: "On Leave",
  droppedOut: "Dropped Out",
  inJob: "In Job",
  payingForward: "Paying Forward",
  paidForward: "Paid Forward",
};

export const nextStage = {
  enrolmentKeyGenerated: ["basicDetailsEntered"],
  createdStudentWithoutExam: [],
  basicDetailsEntered: ["pendingEnglishInterview", "testFailed"],
  testFailed: ["enrolmentKeyGenerated"],
  pendingEnglishInterview: [
    "englishInterviewFail",
    "pendingAlgebraInterview",
    "notReachable",
    "becameDisIntersested",
    "possibleDuplicate",
  ],
  englishInterviewFail: ["pendingEnglishInterview"],
  pendingAlgebraInterview: [
    "algebraInterviewFail",
    "pendingCultureFitInterview",
    "notReachable",
    "becameDisIntersested",
    "possibleDuplicate",
    "tuitionGroup",
  ],
  tuitionGroup: ["pendingAlgebraInterview"],
  algebraInterviewFail: ["pendingAlgebraInterview"],
  pendingCultureFitInterview: [
    "selectedAndJoiningAwaited",
    "cultureFitInterviewFail",
    "notReachable",
    "becameDisIntersested",
    "possibleDuplicate",
  ],
  selected: ["selectedAndJoiningAwaited", "selectedButNotJoined"],
  cultureFitInterviewFail: ["pendingCultureFitInterview"],
  notReachable: [
    "pendingEnglishInterview",
    "pendingAlgebraInterview",
    "pendingCultureFitInterview",
    "becameDisIntersested",
  ],
  selectedAndJoiningAwaited: ["offerLetterSent", "becameDisIntersested"],
  selectedButNotJoined: [],
  offerLetterSent: [
    "pendingTravelPlanning",
    "pendingParentConversation",
    "finalisedTravelPlans",
    "finallyJoined",
    "offerLetterSent",
    "selectedButNotJoined",
  ],
  pendingParentConversation: [
    "finalisedTravelPlans",
    "pendingTravelPlanning",
    "finallyJoined",
    "selectedButNotJoined",
  ],
  pendingTravelPlanning: [
    "finalisedTravelPlans",
    "offerLetterSent",
    "selectedButNotJoined",
  ],
  possibleDuplicate: [
    "pendingEnglishInterview",
    "pendingAlgebraInterview",
    "pendingCultureFitInterview",
  ],
  finalisedTravelPlans: [
    "finallyJoined",
    "offerLetterSent",
    "selectedButNotJoined",
  ],
  becameDisIntersested: [],
  finallyJoined: ["M1"],
  M1: ["M2"],
  M2: ["M3"],
  M3: ["M4"],
  M4: ["M5"],
  M5: ["M6"],
  M6: ["M7", "inJob"],
  M7: ["M8", "inJob"],
  M8: ["M9", "inJob"],
  M9: ["M10", "inJob"],
  M10: ["M11", "M12", "inJob"],
  M11: ["M13", "inJob"],
  M13: ["M15", "inJob"],
  M15: ["M17", "inJob"],
  M17: ["M19", "inJob"],
  M12: ["M14", "inJob"],
  M14: ["M16", "inJob"],
  M16: ["M18", "inJob"],
  M18: ["M19", "inJob"],
  M19: ["M20", "inJob"],
  M20: ["M21", "inJob"],
  M21: ["M22", "inJob"],
  M22: ["inJob"],
  onLeave: [
    "M1",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "M7",
    "M8",
    "M9",
    "M10",
    "M11",
    "M12",
    "M13",
    "M14",
    "M15",
    "M16",
    "M17",
    "M18",
    "M19",
    "M20",
    "M21",
    "M22",
  ],
  droppedOut: [],
  inJob: ["payingForward"],
  payingForward: ["paidForward"],
  paidForward: [],
};

export const campusStatusOptions = {
  present: { label: "Present", display: true },
  onLeave: { label: "On Leave", display: true },
  droppedOut: { label: "Dropped Out", display: true },
  // gotJobLeftCampus: "Got Job & Left the Campus",
  inCampusInterns: { label: "In Campus Interns", display: true },
  inJob: { label: "In Job", display: true },
  som: { label: "SOM", display: false },
  graphicDesign: { label: "Graphic Design", display: false },
  courseCompleted: { label: "Course Completed", display: false },
  // alumniInternStayingInCampus: "Alumni/Interns Staying in Campus",
  teamMember: { label: "Team Member", display: false },
};

export const campusStatusDisplayOptions = Object.keys(campusStatusOptions);

export const states = {
  AN: "Andaman and Nicobar Islands",
  AP: "Andhra Pradesh",
  AR: "Arunachal Pradesh",
  AS: "Assam",
  BR: "Bihar",
  CH: "Chandigarh",
  CT: "Chhattisgarh",
  DN: "Dadra and Nagar Haveli",
  DD: "Daman and Diu",
  DL: "Delhi",
  GA: "Goa",
  GJ: "Gujarat",
  HR: "Haryana",
  HP: "Himachal Pradesh",
  JK: "Jammu and Kashmir",
  JH: "Jharkhand",
  KA: "Karnataka",
  KL: "Kerala",
  LD: "Lakshadweep",
  MP: "Madhya Pradesh",
  MH: "Maharashtra",
  MN: "Manipur",
  ML: "Meghalaya",
  MZ: "Mizoram",
  NL: "Nagaland",
  OR: "Odisha",
  PY: "Puducherry",
  PB: "Punjab",
  RJ: "Rajasthan",
  SK: "Sikkim",
  TN: "Tamil Nadu",
  TG: "Telangana",
  TR: "Tripura",
  UT: "Uttarakhand",
  UP: "Uttar Pradesh",
  WB: "West Bengal",
};

export const genders = {
  1: "Female",
  2: "Male",
  3: "Transgender",
};

export const campus = [
  { id: 1, name: "Pune" },
  { id: 2, name: "Dharamshala" },
  { id: 3, name: "Bangalore" },
  { id: 4, name: "Sarjapura" },
  { id: 5, name: "Tripura" },
  { id: 6, name: "Delhi" },
  { id: 7, name: "Amravati" },
  { id: 8, name: "Jashpur" },
];

export const donor = [
  {
    id: 1,
    name: "Accenture C1",
  },
  {
    id: 2,
    name: "Accenture C2",
  },
  {
    id: 3,
    name: "Accenture C3",
  },
  {
    id: 4,
    name: "Microsoft C1",
  },
  {
    id: 5,
    name: "KPMG C1",
  },
  {
    id: 6,
    name: "LTI",
  },
  {
    id: 7,
    name: "DxC ( EIT)",
  },
  {
    id: 8,
    name: "ACL",
  },
  {
    id: 9,
    name: "Macquarie",
  },
];

export const contactType = ["whatsapp", "primary", "other"];

export const qualification = {
  lessThan10th: 1,
  class10th: 2,
  class12th: 3,
  graduate: 4,
  ba: 5,
  bcom: 6,
  mcom: 7,
  msc: 8,
  bca: 9,
  bsc: 10,
  bba: 11,
};
export const qualificationKeys = {
  1: "Less than 10th",
  2: "Class 10th",
  3: "Class 12th",
  4: "Graduate",
  5: "B.A.",
  6: "B.Com.",
  7: "M.Sc.",
  8: "BCA",
  9: "B.Sc.",
  10: "BBA",
};
export const currentStatus = {
  nothing: 1,
  job: 2,
  study: 3,
  other: 4,
};

const subStage = ["understood", "confused", "need revision"];

export const feedbackableStagesData = {
  pendingEnglishInterview: {
    deadline: 48,
    status: [
      "passed",
      "failed",
      "review",
      "edgeCase",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
      "disinterested",
      "notResponding(1st call done)",
      "notResponding(2nd call done)",
      "notResponding(3rd call done)",
    ],
  },
  pendingAlgebraInterview: {
    deadline: 60,
    status: [
      "passed",
      "failed",
      "review",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
      "disinterested",
      "notResponding(1st call done)",
      "notResponding(2nd call done)",
      "notResponding(3rd call done)",
      "Tution Group",
    ],
  },
  pendingCultureFitInterview: {
    deadline: 48,
    status: [
      "perfectFit",
      "failed",
      "edgeCase",
      "needBased",
      "review",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
      "disinterested",
      "notResponding(1st call done)",
      "notResponding(2nd call done)",
      "notResponding(3rd call done)",
    ],
  },
  pendingTravelPlanning: {
    deadline: 24,
    status: [
      "finalised",
      "reimbursement",
      "failed",
      "joinedMeraki",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
      "notResponding(1st call done)",
      "notResponding(2nd call done)",
      "notResponding(3rd call done)",
      "disinterested",
      "ticketBooked",
      "needFinancialSupport",
      "talkToParents",
    ],
  },
  finalisedTravelPlans: {
    status: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
      "Uninterested",
    ],
  },
  deferredJoining: {
    status: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
  },
  pendingParentConversation: {
    deadline: 24,
    status: [
      "passed",
      "failed",
      "review",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
      "disinterested",
    ],
  },
  algebraInterviewFail: {
    status: [
      "joinedMeraki",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
      "notResponding(1st call done)",
      "notResponding(2nd call done)",
      "notResponding(3rd call done)",
    ],
  },
  englishInterviewFail: {
    status: [
      "joinedMeraki",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
      "notResponding(1st call done)",
      "notResponding(2nd call done)",
      "notResponding(3rd call done)",
    ],
  },
  cultureFitInterviewFail: {
    status: [
      "joinedMeraki",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
      "notResponding(1st call done)",
      "notResponding(2nd call done)",
      "notResponding(3rd call done)",
    ],
  },
  becameDisIntersested: {
    deadline: 60,
    status: [
      "reason",
      "noReason",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
    ],
  },
  tuitionGroup: {
    deadline: 24,
    status: [
      "passed",
      "failed",
      "review",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
      "disinterested",
      "notResponding(1st call done)",
      "notResponding(2nd call done)",
      "notResponding(3rd call done)",
    ],
  },
  requestCallback: {
    deadline: 60,
    status: [
      "resolved",
      "informedTeam",
      "unreachable(1st call done)",
      "unreachable(2nd call done)",
      "unreachable(3rd call done)",
    ],
  },
  M1: {
    status: subStage,
  },

  M2: {
    status: subStage,
  },
  M3: {
    status: subStage,
  },
  M4: {
    status: subStage,
  },
  M5: {
    status: subStage,
  },
  M6: {
    status: subStage,
  },
  M7: {
    status: subStage,
  },
  M8: {
    status: subStage,
  },
  M9: {
    status: subStage,
  },
  M10: {
    status: subStage,
  },
  M11: {
    status: subStage,
  },
  M12: {
    status: subStage,
  },
  M13: {
    status: subStage,
  },
  M14: {
    status: subStage,
  },
  M15: {
    status: subStage,
  },
  M16: {
    status: subStage,
  },
  M17: {
    status: subStage,
  },
  M18: {
    status: subStage,
  },
  M19: {
    status: subStage,
  },
  M20: {
    status: subStage,
  },
  M21: {
    status: subStage,
  },
  M22: {
    status: subStage,
  },
  onLeave: {
    status: ["Medical", "Exams", "Others"],
  },
  selectedButNotJoined: null,
};

export const feedbackableStages = Object.keys(feedbackableStagesData);

export const caste = {
  obc: 1,
  scSt: 2,
  general: 3,
  others: 4,
};
export const religon = {
  hindu: 1,
  islam: 2,
  sikh: 3,
  jain: 4,
  christian: 5,
  others: 6,
  buddhism: 7,
};

export const allTagsForOnlineClass = [
  "interviewPreparationClasses",
  "programmingClasses",
  "duplicate",
];

export const INPUT_PATTERNS = {
  name: /^[\p{L}\p{M}']+$/u,
  replaceName: /[^\p{L}\p{M}']+/gu,
  numbersOnly: /\D/g,
};
